### ISSUE TITLE
ASG network-location filter errors when filtering with security-group

### ISSUE THREAD

**Issue by tim-elliott** [capitalone/cloud-custodian#2664]
The network-location filter errors out when using a condition of `compare: ["resource","security-group"]`.  The relevant parts of the dump are (line numbers relate to released version 0.8.28.2, the same error also happens with code currently in the repo):
```
  File "c:\python27\lib\site-packages\c7n\filters\vpc.py", line 117, in process
    related_sg = self.sg.get_related(resources)
  File "c:\python27\lib\site-packages\c7n\filters\related.py", line 53, in get_related
    related_ids = self.get_related_ids(resources)
  File "c:\python27\lib\site-packages\c7n\resources\asg.py", line 132, in get_related_ids
    cfg = self.configs.get(asg['LaunchConfigurationName'])
AttributeError: 'NoneType' object has no attribute 'get'
```
The problem is that the self.configs object is not initialized before it is being used.  It seems that it is only initialized for a filter that is explicitly of type `launch-config`.  This may require conditionally initializing the `LaunchConfigFilterBase` class in the `NetworkLocation` class if an asg resource is being processed.

**Comment by thisisshi** [comment]
Thanks for the bug report Tim, I've pushed a fix for it here: #2665

**Comment by tim-elliott** [comment]
I updated my local code base with the fix and still get the error, probably because the configs object has never been created.
```
File "<my-local-directory>\custodian\cloud-custodian\c7n\resources\asg.py", line 140, in get_related_ids
    cfg = self.configs.get(asg['LaunchConfigurationName'], {})
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by thisisshi** [comment]
Ah gotcha, misread the initial comment, i'll close the existing pr and take a better look at what's going on. Thanks.

**Comment by thisisshi** [comment]
ok yeah, looks like we're using the `get_related_ids` function before we're initializing for the security-group filter in asg, i have a update that should fix this locally
